name: Publish macOS

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*.*.*'

permissions:
    contents: write

jobs:
    publish:
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-26]

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v6

            - name: Install Node and PNPM
              uses: pnpm/action-setup@v4

            - name: Install dependencies
              run: pnpm install

            - name: Ensure draft release exists
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  version=$(node -p "require('./package.json').version")
                  gh release view "v$version" || gh release create "v$version" --draft --title "$version"

            - name: Build and Publish releases
              env:
                  NODE_OPTIONS: --max-old-space-size=4096
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              uses: nick-invision/retry@v3.0.2
              with:
                  timeout_minutes: 30
                  max_attempts: 3
                  retry_on: error
                  command: |
                      pnpm run publish:mac
                  on_retry_command: pnpm cache delete
